<?php
return [
    'brand' => 'DoRojgar',
    'mark' => 'R',
    'topbar' => 'DoRojgar — Local jobs and hiring',
    'eyebrow' => 'काम मिले, मान बढ़े',
    'hero_h1' => 'Find local work. Hire people you can meet.',
    'hero_p' => 'DoRojgar is the employment planet of Do Galaxy. Employers post roles. Seekers apply with a short note. Staff can verify employers.',
    'footer_blurb' => 'Hyperlocal jobs for shops, factories, offices and gigs.',
    'page_about' => 'DoRojgar connects local employers with seekers. It is a hiring desk, not a gig-only app.',
    'join_cta' => 'Post a job',
    'dir_label' => 'Jobs',
    'owner_role' => 'employer',
    'listing_label' => 'Job',
    'listing_table' => 'dg_jobs',
    'owner_col' => 'employer_id',
    'title_col' => 'title',
    'status_col' => 'status',
    'listing_mode' => 'many',
    'request_table' => 'dg_applications',
    'request_fk' => 'job_id',
    'request_label' => 'Application',
    'fields' => [
        ['title', 'Role title', 'text', true],
        ['company', 'Company', 'text', false],
        ['job_type', 'Type', 'select', true, ['Full-time', 'Part-time', 'Gig', 'Contract', 'Apprentice', 'Internship']],
        ['city', 'City', 'text', true],
        ['locality', 'Locality', 'text', false],
        ['salary_min', 'Salary min (₹)', 'number', false],
        ['salary_max', 'Salary max (₹)', 'number', false],
        ['experience', 'Experience needed', 'text', false],
        ['job_mode', 'Mode', 'select', false, ['Onsite', 'Remote', 'Hybrid']],
        ['skills', 'Skills', 'text', false],
        ['pay', 'Pay (display)', 'text', false],
        ['description', 'Description', 'textarea', true],
    ],
    'request_fields' => [
        ['experience', 'Experience', 'text', false],
        ['resume_url', 'Resume URL', 'text', false],
        ['message', 'Cover note', 'textarea', true],
    ],
    'nav_extra' => [
        ['search', 'Job search'],
        ['resume', 'Resume builder'],
        ['career', 'Career center'],
    ],
    'hero_extra' => [
        ['resume', 'Build resume'],
    ],
    'dash_extra' => [
        'myresume' => 'My resume',
    ],
    'docs' => [
        'gst' => 'Employer GST / Udyam',
        'id' => 'ID proof',
        'address' => 'Workplace address',
    ],
    'packages' => 'Employer profile | ₹999 | Verified hiring desk.
Hiring kit | ₹1,499 | Role templates and shortlist help.
Workforce sprint | ₹2,999 | Multi-role hiring support.',
    'slug' => 'dorojgar',
    'page_privacy' => 'We store the account, listing, documents and requests you submit. Staff see them to verify and support you. We do not sell your data. Write to the contact email to request deletion.',
    'page_terms' => 'This is a listing and operating tool, not a government portal and not legal advice. You are responsible for the accuracy of what you enter. Verification is a human review. Paid packages are fulfilled after staff accept the request.',
    'contact_email' => 'hello@dorojgar.com',
];
