<?php
if (!defined('ABSPATH')) { exit; }
function doudyog_setup(){add_theme_support('title-tag');add_theme_support('post-thumbnails');register_nav_menus(array('primary'=>'Primary Menu'));}
add_action('after_setup_theme','doudyog_setup');
function doudyog_assets(){wp_enqueue_style('doudyog-style',get_stylesheet_uri(),array(),'1.0.1');wp_enqueue_script('doudyog-main',get_template_directory_uri().'/assets/js/main.js',array('jquery'),'1.0.0',true);wp_localize_script('doudyog-main','doudyogAjax',array('ajaxurl'=>admin_url('admin-ajax.php'),'nonce'=>wp_create_nonce('doudyog_nonce')));}
add_action('wp_enqueue_scripts','doudyog_assets');
function doudyog_cpts(){
 register_post_type('business',array('labels'=>array('name'=>'Businesses','singular_name'=>'Business'),'public'=>true,'has_archive'=>true,'menu_icon'=>'dashicons-building','supports'=>array('title','editor','thumbnail','excerpt','custom-fields'),'rewrite'=>array('slug'=>'business')));
 register_post_type('service_package',array('labels'=>array('name'=>'Service Packages','singular_name'=>'Service Package'),'public'=>true,'has_archive'=>true,'menu_icon'=>'dashicons-portfolio','supports'=>array('title','editor','thumbnail','excerpt','custom-fields'),'rewrite'=>array('slug'=>'services')));
 register_post_type('compliance_task',array('labels'=>array('name'=>'Compliance Tasks','singular_name'=>'Compliance Task'),'public'=>true,'has_archive'=>true,'menu_icon'=>'dashicons-clipboard','supports'=>array('title','editor','excerpt','custom-fields'),'rewrite'=>array('slug'=>'compliance')));
 register_post_type('growth_program',array('labels'=>array('name'=>'Growth Programs','singular_name'=>'Growth Program'),'public'=>true,'has_archive'=>true,'menu_icon'=>'dashicons-chart-line','supports'=>array('title','editor','thumbnail','excerpt','custom-fields'),'rewrite'=>array('slug'=>'programs')));
 register_taxonomy('industry',array('business','service_package'),array('labels'=>array('name'=>'Industries'),'public'=>true,'hierarchical'=>true,'rewrite'=>array('slug'=>'industry')));
}
add_action('init','doudyog_cpts');
function doudyog_meta($id,$key,$default=''){ $v=get_post_meta($id,$key,true); return $v?$v:$default; }
function doudyog_create_page($title,$slug,$template){$p=get_page_by_path($slug); if(!$p){$id=wp_insert_post(array('post_title'=>$title,'post_name'=>$slug,'post_status'=>'publish','post_type'=>'page'));}else{$id=$p->ID;} update_post_meta($id,'_wp_page_template',$template); return $id;}
function doudyog_seed(){
 if(get_option('doudyog_seeded_v1')) return;
 $home=doudyog_create_page('Home','home','front-page.php');
 doudyog_create_page('Business Directory','businesses','page-businesses.php'); doudyog_create_page('Services','services','page-services.php'); doudyog_create_page('Compliance Center','compliance-center','page-compliance.php'); doudyog_create_page('Growth Programs','growth-programs','page-growth.php'); doudyog_create_page('Join DoUdyog','join','page-join.php'); doudyog_create_page('Dashboard','dashboard','page-dashboard.php'); doudyog_create_page('Pricing','pricing','page-pricing.php'); doudyog_create_page('Contact','contact','page-contact.php');
 update_option('show_on_front','page'); update_option('page_on_front',$home);
 foreach(array('Manufacturing','Retail','Construction','Hospitality','Services','Education','Healthcare','Technology') as $ind){if(!term_exists($ind,'industry')) wp_insert_term($ind,'industry');}
 $bs=array(array('Sharma Engineering Works','Manufacturing','Pune','GST Verified','Machining, fabrication and industrial components supplier.'),array('Aarambh Retail Network','Retail','Jaipur','MSME Verified','Multi-city retailer looking for suppliers, billing and hiring support.'),array('Nirman BuildMart','Construction','Indore','KYC Verified','Construction material distributor connected with DoNirman and DoVyapaar.'),array('Swagat Hospitality Services','Hospitality','Delhi NCR','GST Verified','Hospitality service operator for events and hotels.'));
 foreach($bs as $b){$id=wp_insert_post(array('post_title'=>$b[0],'post_type'=>'business','post_status'=>'publish','post_excerpt'=>$b[4],'post_content'=>$b[4]));update_post_meta($id,'city',$b[2]);update_post_meta($id,'verification',$b[3]);update_post_meta($id,'employees','11-50');update_post_meta($id,'turnover','₹50L - ₹5Cr');wp_set_object_terms($id,$b[1],'industry');}
 $ss=array(array('MSME Business Profile Setup','Compliance','Create verified business identity and Do Galaxy readiness.','₹999'),array('GST & Compliance Starter','Compliance','GST basics, document checklist and filing calendar.','₹1,999'),array('Digital Storefront Launch','Growth','Get listed across DoUdyog, DoBajar and DoVyapaar.','₹2,999'),array('Hiring & Workforce Kit','People','Connect with DoRojgar for staff and contractors.','₹1,499'),array('Business Growth Audit','Growth','Review operations, sales and technology maturity.','₹4,999'),array('Vendor & Supplier Network','Trade','Discover suppliers and trade partners through DoVyapaar.','₹2,499'));
 foreach($ss as $s){$id=wp_insert_post(array('post_title'=>$s[0],'post_type'=>'service_package','post_status'=>'publish','post_excerpt'=>$s[2],'post_content'=>$s[2]));update_post_meta($id,'type',$s[1]);update_post_meta($id,'price',$s[3]);update_post_meta($id,'duration','3-7 business days');}
 foreach(array('Business Registration Checklist','GST Filing Calendar','MSME/Udyam Registration','Shop Act & Local Licenses','Invoice & Billing Setup','Vendor Agreement Basics') as $t){$id=wp_insert_post(array('post_title'=>$t,'post_type'=>'compliance_task','post_status'=>'publish','post_content'=>'Use this checklist to keep your business clean, credible and growth-ready.'));update_post_meta($id,'status','Open');update_post_meta($id,'priority','Important');}
 foreach(array('Udyog Starter Program','Digital Vyapaar Program','Local to National Growth Sprint','Women Entrepreneurs Circle','Manufacturing Excellence Track','Retail Growth Accelerator') as $p){$id=wp_insert_post(array('post_title'=>$p,'post_type'=>'growth_program','post_status'=>'publish','post_excerpt'=>'Structured program for business growth under Do Galaxy.','post_content'=>'A guided growth program covering identity, digital presence, trade discovery, hiring, compliance and customers.'));update_post_meta($id,'mode','Online + Advisor');update_post_meta($id,'duration','4 weeks');}
 $menu=wp_create_nav_menu('DoUdyog Main Menu'); foreach(array('Home'=>'home','Businesses'=>'businesses','Services'=>'services','Compliance'=>'compliance-center','Growth'=>'growth-programs','Pricing'=>'pricing','Join'=>'join','Dashboard'=>'dashboard') as $label=>$slug){$p=get_page_by_path($slug); if($p){wp_update_nav_menu_item($menu,0,array('menu-item-title'=>$label,'menu-item-object'=>'page','menu-item-object-id'=>$p->ID,'menu-item-type'=>'post_type','menu-item-status'=>'publish'));}} set_theme_mod('nav_menu_locations',array('primary'=>$menu));
 update_option('doudyog_seeded_v1',1);
}
add_action('after_switch_theme','doudyog_seed');
function doudyog_join(){check_ajax_referer('doudyog_nonce','nonce');$name=sanitize_text_field($_POST['business_name']);$id=wp_insert_post(array('post_title'=>$name,'post_type'=>'business','post_status'=>'pending','post_content'=>sanitize_textarea_field($_POST['details']),'post_excerpt'=>sanitize_textarea_field($_POST['details'])));update_post_meta($id,'city',sanitize_text_field($_POST['city']));update_post_meta($id,'phone',sanitize_text_field($_POST['phone']));update_post_meta($id,'verification','Pending Verification');wp_send_json_success(array('message'=>'Your business request has been submitted for review.'));}
add_action('wp_ajax_doudyog_join','doudyog_join');add_action('wp_ajax_nopriv_doudyog_join','doudyog_join');
function doudyog_contact(){check_ajax_referer('doudyog_nonce','nonce');wp_mail(get_option('admin_email'),'New DoUdyog Enquiry',sanitize_textarea_field($_POST['message'])."\nPhone: ".sanitize_text_field($_POST['phone']));wp_send_json_success(array('message'=>'Enquiry received. We will contact you soon.'));}
add_action('wp_ajax_doudyog_contact','doudyog_contact');add_action('wp_ajax_nopriv_doudyog_contact','doudyog_contact');
?>