<?php
return [
    'brand' => 'DoVishram',
    'mark' => 'V',
    'topbar' => 'DoVishram — Trusted stays, short breaks and rest',
    'eyebrow' => 'विश्राम मिले, मन हरे',
    'hero_h1' => 'Find a trusted stay. Host with a verified listing.',
    'hero_p' => 'DoVishram is the rest planet of Do Galaxy. Discover homestays, hotels and short breaks, or list your property and take booking requests.',
    'footer_blurb' => 'Trusted stays and curated rest under Do Galaxy.',
    'page_about' => 'DoVishram helps travellers and families find verified stays, and helps hosts take structured booking requests.',
    'join_cta' => 'List a stay',
    'dir_label' => 'Stays',
    'owner_role' => 'host',
    'listing_label' => 'Stay',
    'listing_table' => 'dg_stays',
    'owner_col' => 'host_id',
    'title_col' => 'title',
    'status_col' => 'verify_status',
    'listing_mode' => 'many',
    'request_table' => 'dg_stay_requests',
    'request_fk' => 'stay_id',
    'request_label' => 'Booking request',
    'fields' => [
        ['title', 'Stay name', 'text', true],
        ['stay_type', 'Type', 'select', true, ['Homestay', 'Hotel', 'Resort', 'Guest house', 'Wellness retreat']],
        ['city', 'City', 'text', true],
        ['area', 'Area / locality', 'text', false],
        ['price_night', 'Price / night', 'text', false],
        ['max_guests', 'Max guests', 'text', false],
        ['amenities', 'Amenities', 'text', false],
        ['about', 'About the stay', 'textarea', false],
    ],
    'request_fields' => [
        ['checkin', 'Check-in', 'date', true],
        ['checkout', 'Check-out', 'date', true],
        ['guests', 'Guests', 'number', true],
        ['message', 'Message', 'textarea', true],
    ],
    'docs' => [
        'id' => 'Host ID',
        'property' => 'Property proof',
        'safety' => 'Safety note',
        'gst' => 'GST if any',
    ],
    'packages' => 'Stay listing setup | ₹999 | Verified host profile.
Weekend rest package | ₹1,999 | Curated 2-night stay help.
Host onboarding | ₹2,499 | Photos, house rules, calendar.',
    'nav_extra' => [
        ['swipe', 'Swipe places'],
        ['wants', 'Want to visit'],
        ['find', 'Find stays'],
        ['packages', 'Rest packages'],
        ['track', 'Track booking'],
    ],
    'hero_extra' => [
        ['swipe', 'Swipe places'],
        ['packages', 'Weekend rest pack'],
    ],
    'slug' => 'dovishram',
    'page_privacy' => 'We store the account, listing, documents and requests you submit. Staff see them to verify and support you. We do not sell your data. Write to the contact email to request deletion.',
    'page_terms' => 'This is a listing and operating tool, not a government portal and not legal advice. You are responsible for the accuracy of what you enter. Verification is a human review. Paid packages are fulfilled after staff accept the request.',
    'contact_email' => 'hello@dovishram.com',
];
