<?php
return [
    'brand' => 'DoSwagat',
    'mark' => 'S',
    'topbar' => 'DoSwagat — Venues, events and hospitality',
    'eyebrow' => 'स्वागत हो, उत्सव हो',
    'hero_h1' => 'Plan the event. Book the venue and the team.',
    'hero_p' => 'DoSwagat is the welcome planet of Do Galaxy. Halls, caterers and hospitality partners take structured event requests.',
    'footer_blurb' => 'Weddings, parties and corporate events in one desk.',
    'page_about' => 'DoSwagat organises venues and hospitality partners so families and firms can request a date, guest count and brief in one place.',
    'join_cta' => 'List a venue',
    'dir_label' => 'Venues',
    'owner_role' => 'partner',
    'listing_label' => 'Venue',
    'listing_table' => 'dg_venues',
    'owner_col' => 'partner_id',
    'title_col' => 'title',
    'status_col' => 'verify_status',
    'listing_mode' => 'many',
    'request_table' => 'dg_event_requests',
    'request_fk' => 'venue_id',
    'request_label' => 'Event request',
    'fields' => [
        ['title', 'Venue / service name', 'text', true],
        ['kind', 'Kind', 'select', true, ['Banquet', 'Lawn', 'Hotel', 'Caterer', 'Decorator', 'Photographer']],
        ['city', 'City', 'text', true],
        ['capacity', 'Capacity', 'text', false],
        ['about', 'About', 'textarea', false],
    ],
    'request_fields' => [
        ['event_date', 'Event date', 'date', true],
        ['guests', 'Guests', 'number', false],
        ['event_type', 'Event type', 'text', false],
        ['budget', 'Budget', 'text', false],
        ['message', 'Brief', 'textarea', true],
    ],
    'docs' => [
        'licence' => 'Trade licence',
        'fire' => 'Fire NOC',
        'gst' => 'GST',
        'menu' => 'Menu / rate card',
    ],
    'packages' => 'Venue listing | ₹1,499 | Verified hall profile.
Wedding desk | ₹4,999 | Venue + caterer + decor shortlist.
Corporate meet | ₹2,999 | Half-day package help.',
    'nav_extra' => [
        ['swipe', 'Shortlist venues'],
        ['shortlist', 'My shortlist'],
        ['brief', 'Event brief'],
        ['packages', 'Event packages'],
        ['track', 'Track request'],
        ['partner', 'Become a partner'],
        ['promise', 'Swagat Promise'],
    ],
    'hero_extra' => [
        ['swipe', 'Shortlist venues'],
        ['packages', 'Event packages'],
        ['track', 'Track a request'],
    ],
    'slug' => 'doswagat',
    'page_privacy' => 'We store the account, listing, documents and requests you submit. Staff see them to verify and support you. We do not sell your data. Write to the contact email to request deletion.',
    'page_terms' => 'This is a listing and operating tool, not a government portal and not legal advice. You are responsible for the accuracy of what you enter. Verification is a human review. Paid packages are fulfilled after staff accept the request.',
    'contact_email' => 'hello@doswagat.com',
];
