<?php
return [
    'brand' => 'DoNirman',
    'mark' => 'N',
    'topbar' => 'DoNirman — India\'s construction marketplace',
    'eyebrow' => 'निर्माण भरोसे से',
    'hero_h1' => 'Build smarter. Estimate cost. Hire verified contractors.',
    'hero_p' => 'Find contractors, compare material prices, estimate construction cost, and keep project notes — the live DoNirman desk, now in this app.',
    'footer_blurb' => 'Contractors, materials, cost estimates and NirmanGyan.',
    'page_about' => 'DoNirman is a construction marketplace: contractor directory, materials bazaar, cost estimator, design briefs and NirmanGyan. It is not an escrow for construction payments.',
    'join_cta' => 'List your trade',
    'dir_label' => 'Contractors',
    'owner_role' => 'contractor',
    'listing_label' => 'Contractor',
    'listing_table' => 'dg_contractors',
    'owner_col' => 'owner_id',
    'title_col' => 'legal_name',
    'status_col' => 'verify_status',
    'listing_mode' => 'one',
    'request_table' => 'dg_project_leads',
    'request_fk' => 'contractor_id',
    'request_label' => 'Project lead',
    'fields' => [
        ['legal_name', 'Firm / name', 'text', true],
        ['trade', 'Trade', 'select', true, ['Civil', 'Mason', 'Electrical', 'Plumbing', 'Painting', 'Carpenter', 'Tile / Flooring', 'Interiors', 'Fabrication', 'Architect']],
        ['city', 'City', 'text', true],
        ['daily_rate', 'Daily rate (₹)', 'number', false],
        ['experience_years', 'Experience (years)', 'number', false],
        ['total_projects', 'Projects completed', 'number', false],
        ['rating', 'Rating (0–5)', 'number', false],
        ['phone', 'Phone', 'text', false],
        ['gstin', 'GSTIN', 'text', false],
        ['available', 'Available now', 'select', false, ['Yes', 'No']],
        ['portfolio', 'Portfolio URL', 'text', false],
        ['about', 'About the work', 'textarea', false],
    ],
    'request_fields' => [
        ['site_city', 'Site city', 'text', false],
        ['start_date', 'Start date', 'date', false],
        ['message', 'Scope', 'textarea', true],
    ],
    'docs' => [
        'gst' => 'GST / Udyam',
        'id' => 'ID',
        'work' => 'Past work photos',
    ],
    'packages' => 'Contractor profile | ₹999 | Verified trade card.
Lead desk | ₹1,999 | Priority inbound leads.
Site pack | ₹4,999 | Estimate checklist with advisor.',
    'slug' => 'donirman',
    'nav_extra' => [
        ['estimate', 'Cost estimator'],
        ['boq', 'BOQ / material RFQ'],
        ['materials', 'Materials'],
        ['gyan', 'NirmanGyan'],
        ['design', 'Design Connect'],
    ],
    'hero_extra' => [
        ['estimate', 'Estimate cost'],
        ['materials', 'Material prices'],
    ],
    'dash_extra' => [
        'estimates' => 'Estimates',
        'projects' => 'Projects',
    ],
    'page_privacy' => 'We store the account, listing, documents, estimates and requests you submit. Staff see them to verify and support you. We do not sell your data. Write to the contact email to request deletion.',
    'page_terms' => 'Estimates are indicative (±10%) from published market rates, not a quotation. This is not a government portal and not legal advice. Verification is a human review.',
    'contact_email' => 'hello@donirman.com',
];
