<?php
return [
    'brand' => 'DoVyapaar',
    'mark' => 'Y',
    'topbar' => 'DoVyapaar — Suppliers, trade and RFQs',
    'eyebrow' => 'व्यापार जुड़े',
    'hero_h1' => 'Find a supplier. Send an RFQ.',
    'hero_p' => 'DoVyapaar is the trade planet of Do Galaxy. Suppliers list category and city. Buyers send item, quantity and a message. Staff can verify suppliers.',
    'footer_blurb' => 'B2B discovery and request-for-quote for MSMEs.',
    'page_about' => 'DoVyapaar is a supplier directory and RFQ desk that sits next to DoUdyog identity.',
    'join_cta' => 'List as supplier',
    'dir_label' => 'Suppliers',
    'owner_role' => 'supplier',
    'listing_label' => 'Supplier',
    'listing_table' => 'dg_suppliers',
    'owner_col' => 'owner_id',
    'title_col' => 'legal_name',
    'status_col' => 'verify_status',
    'listing_mode' => 'one',
    'request_table' => 'dg_rfqs',
    'request_fk' => 'supplier_id',
    'request_label' => 'RFQ',
    'fields' => [
        ['legal_name', 'Firm name', 'text', true],
        ['category', 'Category', 'select', true, ['Raw material', 'Packaging', 'Machinery', 'Wholesale', 'Logistics', 'Other']],
        ['city', 'City', 'text', true],
        ['gstin', 'GSTIN', 'text', false],
        ['moq', 'MOQ', 'text', false],
        ['lead_days', 'Lead time (days)', 'number', false],
        ['about', 'What you supply', 'textarea', false],
    ],
    'nav_extra' => [
        ['products', 'Products'],
        ['leads', 'Trade leads'],
        ['requirement', 'Post requirement'],
        ['board', 'RFQ Center'],
        ['trust', 'Supplier trust'],
    ],
    'hero_extra' => [
        ['requirement', 'Post a requirement'],
    ],
    'request_fields' => [
        ['item', 'Item', 'text', true],
        ['qty', 'Quantity', 'text', false],
        ['message', 'Specs / note', 'textarea', true],
    ],
    'docs' => [
        'gst' => 'GSTIN',
        'udyam' => 'Udyam',
        'catalog' => 'Rate card',
    ],
    'packages' => 'Supplier card | ₹999 | Verified trade listing.
RFQ desk | ₹1,999 | Priority quotes.
DoUdyog + Vyapaar | ₹2,499 | Identity plus trade.',
    'slug' => 'dovyapaar',
    'page_privacy' => 'We store the account, listing, documents and requests you submit. Staff see them to verify and support you. We do not sell your data. Write to the contact email to request deletion.',
    'page_terms' => 'This is a listing and operating tool, not a government portal and not legal advice. You are responsible for the accuracy of what you enter. Verification is a human review. Paid packages are fulfilled after staff accept the request.',
    'contact_email' => 'hello@dovyapaar.com',
];
